export const COLORS = {
  sidebar: "var(--maroon)",
  sidebarActive: "var(--maroon-active)",
  sidebarText: "var(--text-inverse)",
  sidebarMuted: "rgba(255,255,255,0.45)",
  accent: "var(--maroon)",
  accentBtn: "var(--maroon)",
  accentHover: "var(--maroon-hover)",
  white: "#FFFFFF",
  bg: "var(--bg)",
  border: "var(--border)",
  cardBorder: "var(--border)",
  text: "var(--text-primary)",
  muted: "var(--text-secondary)",
  compliant: "var(--success-text)",
  compliantBg: "var(--success-bg)",
  nonCompliant: "var(--error-text)",
  nonCompliantBg: "var(--error-bg)",
  overdue: "var(--error-text)",
  overdueBg: "var(--error-bg)",
  incomplete: "var(--warning-text)",
  incompleteBg: "var(--warning-bg)",
  na: "var(--info-text)",
  naBg: "var(--info-bg)",
};
