import { Entity, PrimaryGeneratedColumn, Column, CreateDateColumn, Index } from 'typeorm';

export enum ReportFormat {
    PDF = 'PDF',
    CSV = 'CSV',
}

export enum ReportExportStatus {
    PENDING = 'pending',
    READY = 'ready',
    FAILED = 'failed',
}

/**
 * Entity: ReportExport (Sprint 5 TT2 — BE Dev 2 / Jhaz owns this table).
 * Maps to `report_exports`. Generation is synchronous (pdfkit/CSV both
 * run well under AC1's 2s budget), so `status` moves straight from
 * PENDING -> READY/FAILED within the same request; the column still
 * exists to support a future async/queued path without a schema change.
 *
 * `file_data` holds the generated bytes directly in Postgres (bytea)
 * since this project has no shared object storage (S3/etc.) configured.
 * `file_path` stores the logical download path returned to the client.
 */
@Entity('report_exports')
export class ReportExport {
    @PrimaryGeneratedColumn('uuid')
    id: string;

    @Index('idx_report_exports_commitment')
    @Column()
    commitment_id: string;

    @Index('idx_report_exports_office')
    @Column({ length: 150 })
    office_id: string;

    @Column({ nullable: true })
    period_id: string;

    @Column({ type: 'enum', enum: ReportFormat })
    format: ReportFormat;

    @Column({ type: 'enum', enum: ReportExportStatus, default: ReportExportStatus.PENDING })
    status: ReportExportStatus;

    @Column({ type: 'text', nullable: true })
    file_path: string | null;

    @Column({ type: 'bytea', nullable: true })
    file_data: Buffer | null;

    @Column({ length: 100, nullable: true })
    mime_type: string | null;

    @Column({ type: 'text', nullable: true })
    error_message: string | null;

    @Column({ length: 100 })
    exported_by: string;

    @CreateDateColumn({ type: 'timestamptz' })
    exported_at: Date;
}